---
apiVersion: triggers.tekton.dev/v1beta1 
kind: Trigger 
metadata:
  name: kfp-deploy-github-trigger 
spec:
  interceptors:
     - ref:
         name: "cel" 
       params:
        - name: filter
          value: (body.ref.split('/')[2] == 'main')
        - name: overlays
          value:
          - expression: body.head_commit.id.truncate(10)
            key: truncated_sha
          - expression: body.ref.split('/')[2]
            key: branch_name
          - expression: body.repository.name
            key: repo_name
          - expression: body.pusher.name
            key: commit_author
  bindings:
    - name: git-branch
      value: $(extensions.branch_name)
    - name: git-short-revision
      value: $(extensions.truncated_sha)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-commit-author
      value: $(body.pusher.name)
  template: 
     ref: kfp-deploy-github-trigger-template