---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: s3-model-retrain-trigger
spec:
  interceptors:
    - ref:
        name: "cel"
      params:
        - name: filter
          value: "body.Records != null && body.Records.size() > 0"
        - name: overlays
          value:
          - expression: "body.Records[0].s3.bucket.name"
            key: s3_bucket
          - expression: "body.Records[0].s3.object.key"
            key: s3_object_key
          - expression: "body.Records[0].eventName"
            key: s3_event_name
  bindings:
    - name: s3-bucket
      value: $(extensions.s3_bucket)
    - name: s3-object-key
      value: $(extensions.s3_object_key)
    - name: s3-event-name
      value: $(extensions.s3_event_name)
  template:
    ref: s3-model-retrain-trigger-template